// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const sessionColumns = `id, parent_session_id, title, scope, project_id, workdir, canonical_workdir, workdir_exists, status, title_source, pinned, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, last_opened_at, deleted_at, summary_message_id, todos`

type sessionScanner interface {
	Scan(dest ...any) error
}

func scanSession(row sessionScanner, i *Session) error {
	return row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.Scope,
		&i.ProjectID,
		&i.Workdir,
		&i.CanonicalWorkdir,
		&i.WorkdirExists,
		&i.Status,
		&i.TitleSource,
		&i.Pinned,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.LastOpenedAt,
		&i.DeletedAt,
		&i.SummaryMessageID,
		&i.Todos,
	)
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    scope,
    project_id,
    workdir,
    canonical_workdir,
    workdir_exists,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary_message_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING ` + sessionColumns + `
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	Scope            string         `json:"scope"`
	ProjectID        sql.NullString `json:"project_id"`
	Workdir          sql.NullString `json:"workdir"`
	CanonicalWorkdir sql.NullString `json:"canonical_workdir"`
	WorkdirExists    int64          `json:"workdir_exists"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.Scope,
		arg.ProjectID,
		arg.Workdir,
		arg.CanonicalWorkdir,
		arg.WorkdirExists,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
	)
	var i Session
	err := scanSession(row, &i)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getLastSession = `-- name: GetLastSession :one
SELECT ` + sessionColumns + `
FROM sessions
WHERE deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSession(ctx context.Context) (Session, error) {
	row := q.queryRow(ctx, q.getLastSessionStmt, getLastSession)
	var i Session
	err := scanSession(row, &i)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT ` + sessionColumns + `
FROM sessions
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := scanSession(row, &i)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT ` + sessionColumns + `
FROM sessions
WHERE parent_session_id is NULL AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := scanSession(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :exec
UPDATE sessions
SET
    title = ?
WHERE id = ?
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) error {
	_, err := q.exec(ctx, q.renameSessionStmt, renameSession, arg.Title, arg.ID)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    summary_message_id = ?,
    cost = ?,
    scope = ?,
    project_id = ?,
    workdir = ?,
    canonical_workdir = ?,
    workdir_exists = ?,
    todos = ?
WHERE id = ?
AND deleted_at IS NULL
RETURNING ` + sessionColumns + `
`

type UpdateSessionParams struct {
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Cost             float64        `json:"cost"`
	Scope            string         `json:"scope"`
	ProjectID        sql.NullString `json:"project_id"`
	Workdir          sql.NullString `json:"workdir"`
	CanonicalWorkdir sql.NullString `json:"canonical_workdir"`
	WorkdirExists    int64          `json:"workdir_exists"`
	Todos            sql.NullString `json:"todos"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.Scope,
		arg.ProjectID,
		arg.Workdir,
		arg.CanonicalWorkdir,
		arg.WorkdirExists,
		arg.Todos,
		arg.ID,
	)
	var i Session
	err := scanSession(row, &i)
	return i, err
}

const updateSessionTitleAndUsage = `-- name: UpdateSessionTitleAndUsage :exec
UPDATE sessions
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error {
	_, err := q.exec(ctx, q.updateSessionTitleAndUsageStmt, updateSessionTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}
